//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add
    {
        public int ID { get; set; }
        public string Img { get; set; }
        public string link_url { get; set; }
    }
}
